services:
  database:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: restaurant
  redis-queue:
    image: redis:6.2.6
    ports:
      - "6379:6379"
